### ISSUE TITLE
A memory release problem in pushing into navigationController many times

### ISSUE THREAD

**Issue by summer9011** [jessedc/JCTiledScrollView#27]
I have a navigationController and a JCTiledScrollViewDemo, I use images in the demo. Then I push the demo into navigation, scale and zoom the scrollView with zoomlevel in 1,2 and 3, i see the memory increase, then I pop out the demo and simulate memory warning, memory not release. also the same as before. Then push and pop twice, or many times, find the memory does not release but increase based on before. 
I what to know why?  is my code problem??

**Comment by jessedc** [comment]
Thanks for the bug report. After many years I've rewritten the demo app and given it a test with instruments this afternoon and I'm not seeing any leaks. 

Cheers!
