### ISSUE TITLE
WWDC 

### ISSUE THREAD

**Issue by pjebs** [jessedc/JCTiledScrollView#34]
Hey Jesse. It's pj from cocoa heads. 
I have an emergency situation and I need to get in touch with someone who's at wwdc before event is over (to ask an app review consultant)
can you get me in touch with some over there who'd be happy to help.

**Comment by jessedc** [comment]
Hey pj,

Send me an email with your email address and I'll invite you to the melbournecocoa slack channel. You can get in touch with most of the community who are over there in the #wwdc channel. 

cheers,

**Comment by pjebs** [comment]
pj@skylove.ly

**Comment by pjebs** [comment]
Jesse how do I use it to write a global message asking anyone at wwdc if they can help me
