### ISSUE TITLE
Some question about JCTiledScrollView

### ISSUE THREAD

**Issue by wenwuwang** [jessedc/JCTiledScrollView#7]
Hi, I'm Jerry
I have sended you a tweet yestoday. My question as follows:
1. I know that you have developed a number of series Metro app, I would like to know, Metro map  is tiled a bitmap images or a single PDF page?
2. There will show a circular mark when I click on your subway map, how do you know the current point is a subway station?
3. Is there better method to get the latitude and longitude of each subway station, do you obtain these data through the Google Map Open Api?

**Comment by maddy04** [comment]
Hi I'm maddy,
I am lookoing for similar app in Anadroid. Do you have any reference in android for the same(Metro app).
